# Tensor 연습 문제 초급

In [2]:
import torch

In [8]:
'''
[1번]
아래 세 리스트 a, b, c를 이용해 이를 pytorch의 float64 type의 tensor로 바꾸고 그것의 크기를 print해 보세요
'''
a = [8, 6, 1]
b = [[1,7,4], [7,2,7]]
c = [[[1,2,3], [4,5,1],[9,8,2]], [[10,6,5], [2,2,7],[6,6,1]]]

# 아래에 풀이 적기
a = torch.FloatTensor(a)
a = a.to(torch.float64)
b = torch.FloatTensor(b)
b = b.to(torch.float64)
c = torch.FloatTensor(c)
c = c.to(torch.float64)

print(a)
print(a.dtype)
print(a.shape)
print(b)
print(b.dtype)
print(b.shape)
print(c)
print(c.dtype)
print(c.shape)

tensor([8., 6., 1.], dtype=torch.float64)
torch.float64
torch.Size([3])
tensor([[1., 7., 4.],
        [7., 2., 7.]], dtype=torch.float64)
torch.float64
torch.Size([2, 3])
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  1.],
         [ 9.,  8.,  2.]],

        [[10.,  6.,  5.],
         [ 2.,  2.,  7.],
         [ 6.,  6.,  1.]]], dtype=torch.float64)
torch.float64
torch.Size([2, 3, 3])


In [9]:
'''
[2번]
아래 두 tensor a와 b의 합을 구하고 그 결과를 출력하세요
'''

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# 아래에 풀이 적기
print(a + b)

tensor([5, 7, 9])


In [11]:
'''
[3번]
아래 tensor의 최솟값과 최댓값을 출력해세요
'''
a = torch.tensor([2, 4, 1, 7, 5])

# 아래에 풀이 적기
print(torch.max(a))
print(torch.min(a))

tensor(7)
tensor(1)


In [12]:
'''
[4번]
모든 값이 0으로 채워진 3 x 4 tensor a를 만드세요
'''

# 아래에 풀이 적기
a = torch.zeros((3, 4))
print(a)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [13]:
'''
[5번]
3 이상 10 이하의 정수로 이루어진 3 x 4 크기의 tensor a를 만드세요
'''

# 아래에 풀이 적기
a = torch.randint(3, 11, (3, 4))
print(a)

tensor([[ 5,  3,  9,  4],
        [ 7,  9, 10,  7],
        [10,  7,  8,  6]])


In [14]:
'''
[6번]
아래 a tensor의 앞에서부터 2번 째 원소와 가장 마지막 원소를 출력하세요
'''
a = torch.tensor([2, 4, 5, 7, 5])

# 아래에 풀이 적기
print(a[1])
print(a[-1])

tensor(4)
tensor(5)


In [16]:
'''
[7번]
아래 a tensor의 크기를 출력하고
이를 3 x 2 x 2 크기를 갖는 b tensor로 변경해보세요
'''
a = torch.randn((2, 6))

# 아래에 풀이 적기
print(a.shape)
a.view(3, 2, 2)

torch.Size([2, 6])


tensor([[[-0.8433, -0.9800],
         [ 0.8368, -1.1756]],

        [[-0.2893,  1.2522],
         [ 0.1592,  1.0212]],

        [[-0.2332,  2.1854],
         [ 0.9628, -1.7520]]])

In [17]:
'''
[8번]
아래 a tensor의 모든 원소의 값을 3배 해 보세요
'''
a = torch.tensor([1, 2, 3, 4])

# 아래에 풀이 적기
a = a * 3
print(a)

tensor([ 3,  6,  9, 12])


In [20]:
'''
[9번]
아래 a tensor의 모든 원소의 값을 제곱 해 보세요
'''
a = torch.tensor([1, 2, 3, 4])

# 아래에 풀이 적기
a = a ** 2
print(a)

tensor([ 1,  4,  9, 16])


# Tensor 연습 문제 중급

In [21]:
'''
[1번]
아래 a tensor를 첫 번째 차원을 기준으로 합을 구하세요
'''
a = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

# 아래에 풀이 적기
torch.sum(a, 0)

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [22]:
'''
[2번]
아래 a tensor에서 5보다 작은 원소만 출력해보세요
'''
a = torch.tensor([0, 1, 9, 2, 8, 3, 7, 4, 6, 5])

# 아래에 풀이 적기
print(a[a < 5])

tensor([0, 1, 2, 3, 4])


In [24]:
'''
[3번]
아래 a tensor에서 짝수번째 원소만 출력해보세요
'''
a = torch.tensor([0, 1, 9, 2, 8, 3, 7, 4, 6, 5])

# 아래에 풀이 적기
print(a[torch.arange(0, a.size(0), 2)])

tensor([0, 9, 8, 7, 6])


In [28]:
'''
[4번]
아래 a tensor의 원소를 반대의 순서로 갖는 tensor b를 만드세요
'''
a = torch.tensor([0, 1, 9, 2, 8, 3, 7, 4, 6, 5])

# 아래에 풀이 적기
b = a[torch.arange(a.size(0)-1,-1, -1)]
print(b)

tensor([5, 6, 4, 7, 3, 8, 2, 9, 1, 0])


In [35]:
'''
[5번]
아래 a tensor를 모든 차원에대해 최소값과 최대값을 구하세요.
'''
a = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

# 아래에 풀이 적기
print(torch.max(a, dim=0))
print(torch.max(a, dim=1))
print(torch.max(a, dim=2))

print(torch.min(a, dim=0))
print(torch.min(a, dim=1))
print(torch.min(a, dim=2))

torch.return_types.max(
values=tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
indices=tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]))
torch.return_types.max(
values=tensor([[7, 8, 9]]),
indices=tensor([[2, 2, 2]]))
torch.return_types.max(
values=tensor([[3, 6, 9]]),
indices=tensor([[2, 2, 2]]))
torch.return_types.min(
values=tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
indices=tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]))
torch.return_types.min(
values=tensor([[1, 2, 3]]),
indices=tensor([[0, 0, 0]]))
torch.return_types.min(
values=tensor([[1, 4, 7]]),
indices=tensor([[0, 0, 0]]))


In [ ]:
'''
[6번]
아래 a tensor의 짝수 행은 모두 0으로 홀수 행은 모두 1로 바꾸세요
'''
a = torch.tensor(
    [
        [0, 0, 0], # 1번째 행
        [1, 1, 1], # 2번째 행
        [2, 2, 2], # 3번째 행
        [3, 3, 3], # 4번째 행
        [4, 4, 4], # 5번째 행
        [5, 5, 5], # 6번째 행
        [6, 6, 6], # 7번째 행
        [7, 7, 7], # 8번째 행
        [8, 8, 8], # 9번째 행
        [9, 9, 9], # 10번째 행
    ]
)

# 아래에 풀이 적기


In [ ]:
'''
[7번]
아래 a tensor의 짝수 열은 모두 0으로 홀수 열은 모두 1로 바꾸세요
'''
a = torch.tensor(
    [
        [0,    0,    0],
        [1,    1,    1],
        [2,    2,    2],
        [3,    3,    3],
        [4,    4,    4],
        [5,    5,    5],
        [6,    6,    6],
        [7,    7,    7],
        [8,    8,    8],
        [9,    9,    9],
    ] # 1열  2열    3열
)

# 아래에 풀이 적기


In [ ]:
'''
[8번]
아래 a tensor를 오름차순과 내림차순으로 정렬해보세요

'''
a = torch.tensor([9, 5, 3, 8, 1, 6, 4, 7, 2, 0])

# 아래에 풀이 적기


# Tensor 연습 문제 고급

In [ ]:
'''
[1번]
아래 a tensor에서 0.3 보다 큰 값의 수를 출력해 보세요
'''
a = torch.randn((2,5,3))

# 아래에 풀이 적기


In [ ]:
'''
[2번]
아래 a tensor에서 음수는 모두 0으로 바꾸세요
'''
a = torch.tensor(
    [
        [-2, -1,  2,  5],
        [ 1,  1, -1,  0],
        [ 2, -1, -1, -1],
        [-1, -1, -1,  3],
        [ 0, -1,  1,  2],
        [ 1, -1,  1, -1],
    ]
)

# 아래에 풀이 적기


In [ ]:
'''
[3번]
아래 a tensor를 sigmoid 함수를 적용시켜보세요
sigmoid 함수 : 1 / (1 + e^(-x))
그리고 torch.sigmoid(a)의 결과와 비교해 보세요
'''
a = torch.tensor([1, 3, 5])

# 아래에 풀이 적기


In [ ]:
'''
[4번]
아래 a tensor를 평균이 0 표준편차가 1이 되도록 정규화 코드를 작성하세요
'''
a = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)

# 아래에 풀이 적기


In [ ]:
'''
[5번]
아래 a tensor의 모든 원소를 오름차순으로 정렬한 후 크기 기준 상위 10%의 원소만 출력해보세요
'''
a = torch.tensor([9, 5, 3, 8, 1, 6, 4, 7, 2, 0])

# 아래에 풀이 적기


In [ ]:
'''
[6번]
아래 a tensor를 1차원으로 평탄화하고, 각 원소가 몇 번 등장하는지 세어 결과를 딕셔너리로 출력하는 코드를 작성하시오
'''
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 아래에 풀이 적기


In [ ]:
'''
[7번]
인덱싱과 슬라이싱을 활용해 아래 a tensor에서 [[4, 5], [7, 8]]를 출력해 보세요
'''
a = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 아래에 풀이 적기
